In [1]:
from pathlib import Path
import random
import pandas as pd

import IMP
import IMP.atom

import sys
sys.path.append("../../src")
from weights import get_random_w_mat

## randomize weights

In [2]:
decoy_df = pd.read_csv(Path("../data/266_decoys/rand1000.csv"), index_col=0)
decoy_df.head()

,pdb,ff,rmsd,w_0_0,w_0_1,w_1_0,w_1_1
0,/wynton/group/sali/mhancock/xray/sample_bench/...,680.593893,0.141288,0.8,0.3,0.2,0.7
1,/wynton/group/sali/mhancock/xray/sample_bench/...,567.037064,0.194410,0.8,0.3,0.2,0.7
2,/wynton/group/sali/mhancock/xray/sample_bench/...,3771.860194,0.042992,0.8,0.3,0.2,0.7
3,/wynton/group/sali/mhancock/xray/sample_bench/...,917.138664,0.160389,0.8,0.3,0.2,0.7
4,/wynton/group/sali/mhancock/xray/sample_bench/...,680.793645,0.137651,0.8,0.3,0.2,0.7

In [6]:
for i in range(1000):
    w_mat = get_random_w_mat(2,2)
    decoy_df.loc[i, "w_0_0"] = w_mat[0,0]
    decoy_df.loc[i, "w_0_1"] = w_mat[0,1]
    decoy_df.loc[i, "w_1_0"] = w_mat[1,0]
    decoy_df.loc[i, "w_1_1"] = w_mat[1,1]

In [7]:
decoy_df.head()

,pdb,ff,rmsd,w_0_0,w_0_1,w_1_0,w_1_1
0,/wynton/group/sali/mhancock/xray/sample_bench/...,680.593893,0.141288,0.616653,0.267505,0.383347,0.732495
1,/wynton/group/sali/mhancock/xray/sample_bench/...,567.037064,0.194410,0.993389,0.571530,0.006611,0.428470
2,/wynton/group/sali/mhancock/xray/sample_bench/...,3771.860194,0.042992,0.700873,0.172079,0.299127,0.827921
3,/wynton/group/sali/mhancock/xray/sample_bench/...,917.138664,0.160389,0.588034,0.638440,0.411966,0.361560
4,/wynton/group/sali/mhancock/xray/sample_bench/...,680.793645,0.137651,0.705625,0.545715,0.294375,0.454285

In [8]:
decoy_df.to_csv(Path("../data/266_decoys/rand1000_rand_w.csv"))

#### correct structure with wrong weights

In [ ]:
decoy_df = pd.read_csv(Path("../data/266_decoys/rand1000.csv"), index_col=0)
decoy_df.head()

In [5]:
decoy_df["pdb"] = "/wynton/home/sali/mhancock/xray/dev/45_synthetic_native_4/data/pdbs/native.pdb"
decoy_df.to_csv("../data/266_decoys/rand1000_w.csv")

#### wrong structure with correct weights

In [9]:
decoy_df = pd.read_csv(Path("../data/266_decoys/rand1000.csv"), index_col=0)
decoy_df.head()

,pdb,ff,rmsd,w_0_0,w_0_1,w_1_0,w_1_1
0,/wynton/group/sali/mhancock/xray/sample_bench/...,789.988948,0.214138,0.437469,0.615200,0.562531,0.384800
1,/wynton/group/sali/mhancock/xray/sample_bench/...,889.430417,0.108996,0.865468,0.180990,0.134532,0.819010
2,/wynton/group/sali/mhancock/xray/sample_bench/...,587.807530,0.186456,0.606549,0.968560,0.393451,0.031440
3,/wynton/group/sali/mhancock/xray/sample_bench/...,4687.550984,0.056656,0.984052,0.395749,0.015948,0.604251
4,/wynton/group/sali/mhancock/xray/sample_bench/...,3015.672514,0.067009,0.771339,0.401298,0.228661,0.598702

In [11]:
decoy_df["w_0_0"] = .9
decoy_df["w_0_1"] = .1
decoy_df["w_1_0"] = .1
decoy_df["w_1_1"] = .9
decoy_df.to_csv("../data/266_decoys/rand1000_c.csv")